// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQiGx-wVJdHf1mYWPXCtGCn_-93DtWnUY',
    appId: '1:423092882247:web:6f2e618a791e16caa2da62',
    messagingSenderId: '423092882247',
    projectId: 'recipes-application-2e959',
    authDomain: 'recipes-application-2e959.firebaseapp.com',
    storageBucket: 'recipes-application-2e959.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVpHU6L1q4YFNrSPT2ZZjZr2_Rux22n8',
    appId: '1:423092882247:android:211ea7ea7204fc22a2da62',
    messagingSenderId: '423092882247',
    projectId: 'recipes-application-2e959',
    storageBucket: 'recipes-application-2e959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB426kExr4ohqqT2dhMjUKAWaZRC5n-sKg',
    appId: '1:423092882247:ios:03eb6f3b6db3b930a2da62',
    messagingSenderId: '423092882247',
    projectId: 'recipes-application-2e959',
    storageBucket: 'recipes-application-2e959.appspot.com',
    iosClientId: '423092882247-h8too58mkl0irhrmk8v97p8if1r7gtkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRecipesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB426kExr4ohqqT2dhMjUKAWaZRC5n-sKg',
    appId: '1:423092882247:ios:03eb6f3b6db3b930a2da62',
    messagingSenderId: '423092882247',
    projectId: 'recipes-application-2e959',
    storageBucket: 'recipes-application-2e959.appspot.com',
    iosClientId: '423092882247-h8too58mkl0irhrmk8v97p8if1r7gtkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRecipesApplication',
  );
}
